#!/bin/sh
# Copyright 2012, Tim Henigan <tim.henigan@gmail.com>
tmpdir=$(perl -e "use File::Temp qw(tempdir); print tempdir('/tmp/git-diffall.XXXXX')")
trap 'rm -rf "$tmpdir"' EXIT
perl "$(git --exec-path)/git-diffall--lib" "$tmpdir" $@
if test $? = 0
then
	LOCAL="$tmpdir/left"
	REMOTE="$tmpdir/right"
	SUBDIRECTORY_OK=1
	TOOL_MODE=diff
	. "$(git --exec-path)/git-sh-setup"
	. "$(git --exec-path)/git-mergetool--lib"
	merge_tool="$(get_merge_tool)"
	run_merge_tool "$merge_tool" false
fi
